version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: salon-suite-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "14333:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7.2-alpine
    container_name: salon-suite-redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: salon-suite-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15673:15672"

volumes:
  sqlserver-data:
